### ISSUE TITLE
MySql

### ISSUE THREAD

**Issue by herasimau** [shardis/spring-angular2-starter#12]
Hi,
i was trying to connect your app with MySql,
but i have some problems.

1) Need i put UUID into the table BLOG_POST and USER? 
(if yes which format it will be BigInt? if no how to tell spring to don't touch this field)
2) Which time format to choose in mysql for LocalDateTime ? timestramp or datetime ?

Thank you

**Comment by kucharzyk** [comment]
Hi,
Best way at the begining  is to use hbm2ddl option and let Hibernate to generate schema automagically for you.

But if you want to now. 

1) I would use binary type for uuid or change field in entity to String and store it as varchar.
2) I would use timestamp

**Comment by herasimau** [comment]
Thank you
