### ISSUE TITLE
Config server

### ISSUE THREAD

**Issue by kucharzyk** [shardis/spring-angular2-starter#20]
- [x]  Create configuration server
- [x]  Move part of configuration to external repository
- [x]  Pass configuration server repository url to docker via environment variable

**Comment by kucharzyk** [comment]
Now we have config service, but it's not yet finished.

Configurations must be moved to new repository and I have to add option to pass configuration repo from docker-compose.yml

**Comment by tsukhu** [comment]
There is one issue that I noticed when we run all the services . The config server is throwing an exception
![image](https://cloud.githubusercontent.com/assets/846306/17769882/800c056e-6558-11e6-8f32-b6002caea940.png)
I tried to include this dependency .. but still get the same error
 <dependency>
    		<groupId>com.jcraft</groupId>
    		<artifactId>jsch</artifactId>
    		<version>0.1.53</version>
		</dependency>

**Comment by kucharzyk** [comment]
I didn't notice this exception. I'll check it

**Comment by tsukhu** [comment]
I agree .. we probably also should enable https for the production builds (off-course not related to this issue).

**Comment by kucharzyk** [comment]
I don't get exception like yours. 

Internet says that such exception could be caused by broken jar in classpath.
Could you check yours jars in shardis-config./ratget directory. Maybe one of them is broken?

**Comment by tsukhu** [comment]
ok - I cleaned up maven , refreshed the source code and docker .. Now it works !!
