### ISSUE TITLE
Make UI Text responsive

### ISSUE THREAD

**Issue by tsukhu** [shardis/spring-angular2-starter#33]
The Angular 2 text headers are not responsive in md-title and md-subtitle .. Ideally we would like the text to be resized to fit or optionally displayed

![image](https://cloud.githubusercontent.com/assets/846306/17801924/ac024298-660a-11e6-8b4b-51a0475a62f9.png)

**Comment by kucharzyk** [comment]
I've changed md-card-header to md-card-title-group and removed h1 from md-card-title.

Now it looks better.

![responsive](https://cloud.githubusercontent.com/assets/5682894/17821587/ae6bbd1e-6652-11e6-90a2-b23ba1b587fa.png)
