### ISSUE TITLE
Not really an issue: Why is standalone (non-docker) usage no longer recommended?

### ISSUE THREAD

**Issue by rijadsacirovic** [shardis/spring-angular2-starter#34]
Can you explain why it is not recommended? what issues, risks are involved?
What would i need to do in order to make it usable standalone?

**Comment by kucharzyk** [comment]
Standalone usage is still possible but with every service it will be harder and harder.
Lifer with docker is just easier.

Suppose you have 10 multiservices to start manually and one or more databases.
With docker you can use one command to run everything.
