### ISSUE TITLE
Add support for automated API documentation using TDD and Spring REST Docs

### ISSUE THREAD

**Issue by tsukhu** [shardis/spring-angular2-starter#38]
All microservices exposing REST APIS need to be documented . Spring REST Docs provides a TDD based API documentation framework based on AsciiDoc and ensures that the API documentation are always updated along with the tests. Another important feature being the ability to handle hypermedia and HATEOAS APIs. Since the starter project has one API service (shardis-api) , this will be implemented for this microservice as a sample.

**Comment by kucharzyk** [comment]
It's working. Thanks
