### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by herasimau** [shardis/spring-angular2-starter#41]
When running mvn install,
i see exсeption and Build failure.

Docker is runnig...

![immagine](https://cloud.githubusercontent.com/assets/14974515/18015826/a9beefb2-6bc9-11e6-9bd7-b310316927f6.png)

**Comment by kucharzyk** [comment]
You need to setup environment variables for docker.

In windows you have to it manually (except windows 10 pro with docker on hyper-v)

After starting docker run the following command  to see variables you need to set

```
C:\dev\projects\spring-angular2-starter>docker-machine env
SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.99.100:2376
SET DOCKER_CERT_PATH=C:\Users\tomasz\.docker\machine\machines\default
SET DOCKER_MACHINE_NAME=default
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('docker-machine env') DO @%i
```

after then set this values as environment variables

**Comment by smile2014** [comment]
Do you use any IDE as a development tool

**Comment by kucharzyk** [comment]
I'm using InteliJ IDEA. It's the best IDE for me.

**Comment by tsukhu** [comment]
I've been using STS 3.8 for development. That too works fine , given the spring source support.

**Comment by smile2014** [comment]
@kucharzyk  thank you .
