### ISSUE TITLE
Lombok

### ISSUE THREAD

**Issue by tomaszkolodziej** [shardis/spring-angular2-starter#46]
Add lombok support. 

Why lombok was removed in version 1.9.0? Is there was any reason to remove lombok from project?

**Comment by kucharzyk** [comment]
Lombok is great tool and I use it everyday in my work but:
* It may not survive changes in java 9
* You need lombok plugin for your IDE (some users may be disoriented)
* It may be source of problems if You don't know how it works like @EqualsAndHashcode which don't call superclass by default.
* Everyone can add lombok on his own. Delombok is harder.

Do you think it's worth adding Lombok?

**Comment by tomaszkolodziej** [comment]
- I  don't know nothing about java 9 :)
- agree, some users may be disoriented to install lombok plugin in intellij or other ide,

Ok, may better option to wait. I will wait for java 9 and open this question/task or (may be better solution) add lombok plugin on my own (after java 9 released).

**Comment by kucharzyk** [comment]
I've checked current status of Lombok:
* There was no single commit for about 3 moths.
* There are still some issues with upcomming jdk9

**Comment by tsukhu** [comment]
I agree ..
Ideally lets keep the starter project related to the Spring and Angular 2 eco-system only. Add-ons like lombok should be left to the developers discretion

**Comment by kucharzyk** [comment]
In the future We can consider Immutables or AutoValue as better (but less powerfull) alternatives.

https://dzone.com/articles/lombok-autovalue-and-immutables

For now I'm closing this issue
