### ISSUE TITLE
Error: Cannot find module 'joi'

### ISSUE THREAD

**Issue by andreimladin** [shardis/spring-angular2-starter#8]
Running "mvn spring-boot:run -P dev -Dspring.profiles.active=dev" in sharedis-ui, I've got this:
- Error: Cannot find module 'joi'

Do you have any idea why? What should I do to fix it?

**Comment by shardis** [comment]
It looks like you don't have joi module installed.

It works for me. Joi is dependency of webpack-validator.

Temporary solution is ```npm install joi``` but it's interesting

Can you provide more details:
* Do you use master version?
* Which operating system do you use?
* Was your project directory clean or you had node_modules from previous version?
* You can also provide more logs? Maybe there was errors before?

**Comment by andreimladin** [comment]
Fix when I installed it separately.
Answers:
* I used master
* OS x
* It's the first time when I used it, so it was clean
* Now I'm not with my laptop to provide logs

**Comment by shardis** [comment]
Unfortunately I test my code only on Linux and Windows and I don't have access to OSX machine.

I've added explicit joi dependency in package.json master branch. 

It should resolve this issue.

**Comment by andreimladin** [comment]
Fixed. Thanks
